language: php

php:
  - 7

env:
  matrix:
    - TYPO3_VERSION="^7.6"
    - TYPO3_VERSION="^8.7"
    - TYPO3_VERSION="8.7.4"
    - TYPO3_VERSION="8.7.5"
    - TYPO3_VERSION="8.7.6"
    - TYPO3_VERSION="dev-TYPO3_8-7"
    - TYPO3_VERSION="dev-master as 8.7.0"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="t3_fluid_travis_test";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'
